[package]
name = "spellck"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_urlencoded = "0.7.0"
serde = { version = "1.0.130", features = ["derive"] }
annotate-snippets = { version = "0.9.1", features = ["color"] }
ureq = { version = "2.3.1", features = ["json"] }
